//export const WORDS = ["code", "frontend", "programming"];
export const THEMES_US = [
  {
    theme: "Sport",
    words: [
      "Football",
      "Basketball",
      "Tennis",
      "Swimming",
      "Cycling",
      "Athletics",
      "Gymnastics",
      "Volleyball",
      "Skiing",
      "Boxing",
    ],
  },
  {
    theme: "Movies and Actors",
    words: [
      "Adventure",
      "Fantasy",
      "Comedy",
      "Drama",
      "Thriller",
      "Actor",
      "Actress",
      "Director",
      "Script",
      "Cinematography",
      "Oscar",
      "Blockbuster",
      "Cameo",
      "Sequel",
      "Premiere",
      "Soundtrack",
      "Casting",
      "Genre",
      "Screenplay",
      "Dialogue",
    ],
  },
  {
    theme: "Countries and Capitals",
    words: [
      "Argentina",
      "Australia",
      "Brazil",
      "Canada",
      "China",
      "France",
      "Germany",
      "India",
      "Italy",
      "Japan",
      "Mexico",
      "Russia",
      "South Africa",
      "Spain",
      "Sweden",
      "Turkey",
      "United Kingdom",
      "United States",
      "Egypt",
      "Netherlands",
    ],
  },
  {
    theme: "Animals and Plants",
    words: [
      "Elephant",
      "Tiger",
      "Giraffe",
      "Kangaroo",
      "Penguin",
      "Cheetah",
      "Dolphin",
      "Peacock",
      "Koala",
      "Butterfly",
      "Sunflower",
      "Oak Tree",
      "Rose",
      "Bee",
      "Octopus",
      "Crocodile",
      "Orchid",
      "Panda",
      "Cactus",
      "Dragonfly",
    ],
  },
  {
    theme: "Musical instruments",
    words: [
      "Guitar",
      "Piano",
      "Violin",
      "Trumpet",
      "Flute",
      "Drums",
      "Saxophone",
      "Accordion",
      "Harp",
      "Clarinet",
      "Trombone",
      "Cello",
      "Banjo",
      "Xylophone",
      "Bagpipes",
      "Mandolin",
      "Harmonica",
      "Cymbals",
      "Organ",
      "Djembe",
    ],
  },
];

export const THEMES_RU = [
  {
    theme: "Спорт",
    words: [
      "Легкая атлетика",
      "Футбол",
      "Баскетбол",
      "Теннис",
      "Плавание",
      "Велоспорт",
      "Гимнастика",
      "Волейбол",
      "Лыжи",
      "Бокс",
    ],
  },
  {
    theme: "Фильмы и Актеры",
    words: [
      "Приключения",
      "Фэнтези",
      "Комедия",
      "Драма",
      "Триллер",
      "Актер",
      "Актриса",
      "Режиссер",
      "Сценарий",
      "Кинематография",
      "Оскар",
      "Блокбастер",
      "Камео",
      "Сиквел",
      "Премьера",
      "Саундтрек",
      "Кастинг",
      "Жанр",
      "Сценарий",
      "Диалог",
    ],
  },
  {
    theme: "Страны и Столицы",
    words: [
      "Аргентина",
      "Австралия",
      "Бразилия",
      "Канада",
      "Китай",
      "Франция",
      "Германия",
      "Индия",
      "Италия",
      "Япония",
      "Мексика",
      "Россия",
      "Южная Африка",
      "Испания",
      "Швеция",
      "Турция",
      "Великобритания",
      "Соединенные Штаты",
      "Египет",
      "Нидерланды",
    ],
  },
  {
    theme: "Животные и Растения",
    words: [
      "Слон",
      "Тигр",
      "Жираф",
      "Кенгуру",
      "Пингвин",
      "Гепард",
      "Дельфин",
      "Павлин",
      "Коала",
      "Бабочка",
      "Подсолнечник",
      "Дуб",
      "Роза",
      "Пчела",
      "Осьминог",
      "Крокодил",
      "Орхидея",
      "Панда",
      "Кактус",
      "Стрекоза",
    ],
  },
  {
    theme: "Музыкальные инструменты",
    words: [
      "Гитара",
      "Пианино",
      "Скрипка",
      "Труба",
      "Флейта",
      "Барабаны",
      "Саксофон",
      "Аккордеон",
      "Арфа",
      "Кларнет",
      "Тромбон",
      "Виолончель",
      "Банджо",
      "Ксилофон",
      "Волынка",
      "Мандолина",
      "Гармоника",
      "Тарелки",
      "Орган",
      "Джембе",
    ],
  },
];

export const KEYBOARD_LETTERS_US = Array.from("ABCDEFGHIJKLMNOPQRSTUVWXYZ");
export const KEYBOARD_LETTERS_RU = Array.from(
  "АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ",
);
